const sessionTypes = {
  UPDATE_FRONT_LEFT_PAW: 'UPDATE_FRONT_LEFT_PAW',
  UPDATE_FRONT_RIGHT_PAW: 'UPDATE_FRONT_RIGHT_PAW',
  UPDATE_BACK_LEFT_PAW: 'UPDATE_BACK_LEFT_PAW',
  UPDATE_BACK_RIGHT_PAW: 'UPDATE_BACK_RIGHT_PAW',
};

export default sessionTypes;