const sessionTypes = {
  UPDATE_FRONT_LEFT_PAW: 'UPDATE_FRONT_LEFT_PAW',
  UPDATE_FRONT_RIGHT_PAW: 'UPDATE_FRONT_RIGHT_PAW',
  UPDATE_BACK_LEFT_PAW: 'UPDATE_BACK_LEFT_PAW',
  UPDATE_BACK_RIGHT_PAW: 'UPDATE_BACK_RIGHT_PAW',

  UPDATE_FRONT_LEFT_PAW_STATUS: 'UPDATE_FRONT_LEFT_PAW_STATUS',
  UPDATE_FRONT_RIGHT_PAW_STATUS: 'UPDATE_FRONT_RIGHT_PAW_STATUS',
  UPDATE_BACK_LEFT_PAW_STATUS: 'UPDATE_BACK_LEFT_PAW_STATUS',
  UPDATE_BACK_RIGHT_PAW_STATUS: 'UPDATE_BACK_RIGHT_PAW_STATUS',

  UPDATE_FRONT_LEFT_PAW_OUTCOME: 'UPDATE_FRONT_LEFT_PAW_OUTCOME',
  UPDATE_FRONT_RIGHT_PAW_OUTCOME: 'UPDATE_FRONT_RIGHT_PAW_OUTCOME',
  UPDATE_BACK_LEFT_PAW_OUTCOME: 'UPDATE_BACK_LEFT_PAW_OUTCOME',
  UPDATE_BACK_RIGHT_PAW_OUTCOME: 'UPDATE_BACK_RIGHT_PAW_OUTCOME',

  UPDATE_FRONT_LEFT_PAW_BEHAVIOR: 'UPDATE_FRONT_LEFT_PAW_BEHAVIOR',
  UPDATE_FRONT_RIGHT_PAW_BEHAVIOR: 'UPDATE_FRONT_RIGHT_PAW_BEHAVIOR',
  UPDATE_BACK_LEFT_PAW_BEHAVIOR: 'UPDATE_BACK_LEFT_PAW_BEHAVIOR',
  UPDATE_BACK_RIGHT_PAW_BEHAVIOR: 'UPDATE_BACK_RIGHT_PAW_BEHAVIOR',

  COMPLETE_FRONT_LEFT_PAW: 'COMPLETE_FRONT_LEFT_PAW',
  COMPLETE_FRONT_RIGHT_PAW: 'COMPLETE_FRONT_RIGHT_PAW',
  COMPLETE_BACK_LEFT_PAW: 'COMPLETE_BACK_LEFT_PAW',
  COMPLETE_BACK_RIGHT_PAW: 'COMPLETE_BACK_RIGHT_PAW',
};

export default sessionTypes;